media: media

content:
  - name: notes
    label: Law Notes
    type: collection
    path: content/notes
    filename: "{{date:YYYY-MM-DD}}-{{slug}}.md"
    view:
      fields: [title, date, tags, cover_image]  # Shows tags in list view
    fields:
      - name: title
        label: Title
        type: string
        required: true
      - name: cover_image
        label: Cover Image or Thumbnail
        type: image
      - name: date
        label: Date
        type: date
        default: today
      - name: tags
        label: Tags
        type: list
        description: Add one or more tags (e.g., Constitutional Law, Judicial Review)
      - name: body
        label: Note Content
        type: rich-text