media: media  # Assumes your media/uploads folder is called 'media' — change if different (e.g., 'assets/media')

content:
  - name: notes
    label: Law Notes
    type: collection
    path: content/notes  # Folder where your note Markdown files are stored
    filename: "{{date:YYYY-MM-DD}}-{{slug}}.md"  # Safe naming: date + slug to avoid duplicates
    view:
      fields: [title, date, category, cover_image]  # Optional: controls what columns show in the list view
    fields:
      - name: title
        label: Title
        type: string
        required: true
      - name: cover_image
        label: Cover Image or Thumbnail
        type: image
      - name: date
        label: Date
        type: date
        default: today
      - name: category
        label: Category
        type: select  # This creates a dropdown
        options:
          - Contracts
          - Torts
          - Criminal Law
          # Add more categories here if needed, e.g. - Constitutional Law
      - name: body
        label: Note Content
        type: rich-text  # This gives the full WYSIWYG editor for your main notes