media: media

content:
  - name: notes
    label: Law Notes
    type: collection
    path: content/notes
    filename: "{{date:YYYY-MM-DD}}-{{slug}}.md"
    view:
      fields: [title, date, category, cover_image]
    fields:
      - name: title
        label: Title
        type: string
        required: true
      - name: cover_image
        label: Cover Image or Thumbnail
        type: image
      - name: date
        label: Date
        type: date
        default: today
      - name: category
        label: Category
        type: select
        options:
          values: [Contracts, Torts, Criminal Law]
      - name: body
        label: Note Content
        type: rich-text
