media: media

content:
  - name: notes
    label: Law Notes
    type: collection
    path: content/notes
    filename_template: "{{slug}}"
    fields:
      - name: title
        label: Title
        type: string
        required: true
      - name: cover_image
        label: Cover Image or Thumbnail
        type: image
      - name: date
        label: Date
        type: date
        default: today
      - name: category
        label: Category
        type: string
        options:
          - Contracts
          - Torts
          - Criminal Law
          - Property
          - Constitutional
          - Evidence
          - Civil Procedure
          - Common Law
          - Historical
          - Other
      - name: tags
        label: Tags
        type: string
        list: true
      - name: body
        label: Note Content
        type: rich-text
        required: true
      - name: attachments
        label: Additional Files (PDFs, PPTs, etc.)
        type: file
        list: true
      - name: draft
        label: Draft (hide from public site)
        type: boolean
        default: false

  - name: files
    label: Site Files
    type: files
    path: ""
    # This line unlocks the full file browser for index.html, tags.html, etc.